const showData = [{
        "score":24.162006,
        "show":{"id":11,"url":"https://www.tvmaze.com/shows/11/gotham","name":"Gotham","type":"Scripted","language":"English","genres":["Drama","Action","Crime", "Thriller"],"status":"Ended","runtime":60,"premiered":"2014-09-22","officialSite":"http://www.fox.com/gotham","schedule":{"time":"20:00","days":["Thursday"]},"rating":{"average":7.7},"weight":94,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":38049,"thetvdb":274431,"imdb":"tt3749900"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/189/474715.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/189/474715.jpg"},"summary":"<p>The good. The evil. The beginning.</p><p>Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker?</p><p><b>Gotham </b>is an origin story of the great DC Comics Super-Villains and vigilantes, revealing an entirely new chapter that has never been told. It follows one cop's rise through a dangerously corrupt city teetering between good and evil, and chronicles the birth of one of the most popular super heroes of our time.</p>","updated":1606329975,"_links":{"self":{"href":"https://api.tvmaze.com/shows/11"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1616387"}}}},
    {
        "score":23.162006,
        "show":{"id":9,"url":"https://www.tvmaze.com/shows/9/revenge","name":"Revenge","type":"Scripted","language":"English","genres":["Drama","Thriller", "Action"],"status":"Ended","runtime":60,"premiered":"2011-09-21","officialSite":null,"schedule":{"time":"22:00","days":["Sunday"]},"rating":{"average":7.8},"weight":78,"network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":28387,"thetvdb":248837,"imdb":"tt1837642"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/82/206879.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/82/206879.jpg"},"summary":"<p>This is not a story about forgiveness; <b>Revenge</b> is a show about retribution. Meet Emily Thorne, the newest resident of The Hamptons. When she was a little girl (and known as Amanda Clarke) her father, David Clarke, was framed for a horrific crime and subsequently sent to prison. While serving his time, the conspirators plotted and murdered David in order to prevent the truth from coming out. Emily is now back with a new identity and ready to take vengeance on the people that murdered her father and stole her childhood.</p>","updated":1577712742,"_links":{"self":{"href":"https://api.tvmaze.com/shows/9"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/154117"}}}},
    {
        "score":21.162006,
        "show":{"id":7,"url":"https://www.tvmaze.com/shows/7/homeland","name":"Homeland","type":"Scripted","language":"English","genres":["Drama","Thriller", "Crime"],"status":"Ended","runtime":60,"premiered":"2011-10-02","officialSite":"http://www.sho.com/sho/homeland/home","schedule":{"time":"21:00","days":["Sunday"]},"rating":{"average":8.2},"weight":98,"network":{"id":9,"name":"Showtime","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":27811,"thetvdb":247897,"imdb":"tt1796960"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/230/575652.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/230/575652.jpg"},"summary":"<p>The winner of 6 Emmy Awards including Outstanding Drama Series, <b>Homeland</b> is an edge-of-your-seat sensation. Marine Sergeant Nicholas Brody is both a decorated hero and a serious threat. CIA officer Carrie Mathison is tops in her field despite being bipolar. The delicate dance these two complex characters perform, built on lies, suspicion, and desire, is at the heart of this gripping, emotional thriller in which nothing short of the fate of our nation is at stake.</p>","updated":1590059677,"_links":{"self":{"href":"https://api.tvmaze.com/shows/7"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1801029"}}}},
    {
        "score":27.162006,
        "show":{"id":4,"url":"https://www.tvmaze.com/shows/4/arrow","name":"Arrow","type":"Scripted","language":"English","genres":["Drama","Action","Science-Fiction", "Thriller"],"status":"Ended","runtime":60,"premiered":"2012-10-10","officialSite":"http://www.cwtv.com/shows/arrow","schedule":{"time":"21:00","days":["Tuesday"]},"rating":{"average":7.4},"weight":97,"network":{"id":5,"name":"The CW","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":30715,"thetvdb":257655,"imdb":"tt2193021"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/213/534017.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/213/534017.jpg"},"summary":"<p>After a violent shipwreck, billionaire playboy Oliver Queen was missing and presumed dead for five years before being discovered alive on a remote island in the Pacific. He returned home to Starling City, welcomed by his devoted mother Moira, beloved sister Thea and former flame Laurel Lance. With the aid of his trusted chauffeur/bodyguard John Diggle, the computer-hacking skills of Felicity Smoak and the occasional, reluctant assistance of former police detective, now beat cop, Quentin Lance, Oliver has been waging a one-man war on crime.</p>","updated":1612570697,"_links":{"self":{"href":"https://api.tvmaze.com/shows/4"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1744752"}}}},
    {
        "score":11.162006,
        "show":{"id":3,"url":"https://www.tvmaze.com/shows/3/bitten","name":"Bitten","type":"Scripted","language":"English","genres":["Drama","Horror","Romance","Science-Fiction"],"status":"Ended","runtime":60,"premiered":"2014-01-11","officialSite":"http://bitten.space.ca/","schedule":{"time":"22:00","days":["Friday"]},"rating":{"average":7.5},"weight":71,"network":{"id":7,"name":"CTV Sci-Fi Channel","country":{"name":"Canada","code":"CA","timezone":"America/Halifax"}},"webChannel":null,"externals":{"tvrage":34965,"thetvdb":269550,"imdb":"tt2365946"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/15.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/15.jpg"},"summary":"<p>Based on the critically acclaimed series of novels from Kelley Armstrong. Set in Toronto and upper New York State, <b>Bitten</b> follows the adventures of 28-year-old Elena Michaels, the world's only female werewolf. An orphan, Elena thought she finally found her \"happily ever after\" with her new love Clayton, until her life changed forever. With one small bite, the normal life she craved was taken away and she was left to survive life with the Pack.</p>","updated":1603936716,"_links":{"self":{"href":"https://api.tvmaze.com/shows/3"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/631862"}}}},
    {
        "score":13.162006,
        "show":{"id":2,"url":"https://www.tvmaze.com/shows/2/person-of-interest","name":"Person of Interest","type":"Scripted","language":"English","genres":["Action","Crime","Science-Fiction"],"status":"Ended","runtime":60,"premiered":"2011-09-22","officialSite":"http://www.cbs.com/shows/person_of_interest/","schedule":{"time":"22:00","days":["Tuesday"]},"rating":{"average":8.9},"weight":94,"network":{"id":2,"name":"CBS","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":28376,"thetvdb":248742,"imdb":"tt1839578"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/163/407679.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/163/407679.jpg"},"summary":"<p>You are being watched. The government has a secret system, a machine that spies on you every hour of every day. I know because I built it. I designed the Machine to detect acts of terror but it sees everything. Violent crimes involving ordinary people. People like you. Crimes the government considered \"irrelevant\". They wouldn't act so I decided I would. But I needed a partner. Someone with the skills to intervene. Hunted by the authorities, we work in secret. You'll never find us. But victim or perpetrator, if your number is up, we'll find you.</p>","updated":1588773151,"_links":{"self":{"href":"https://api.tvmaze.com/shows/2"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/659372"}}}},
    {
        "score":14.162006,
        "show":{"id":1,"url":"https://www.tvmaze.com/shows/1/under-the-dome","name":"Under the Dome","type":"Scripted","language":"English","genres":["Drama","Science-Fiction","Thriller"],"status":"Ended","runtime":60,"premiered":"2013-06-24","officialSite":"http://www.cbs.com/shows/under-the-dome/","schedule":{"time":"22:00","days":["Thursday"]},"rating":{"average":6.5},"weight":95,"network":{"id":2,"name":"CBS","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":25988,"thetvdb":264492,"imdb":"tt1553656"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/81/202627.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/81/202627.jpg"},"summary":"<p><b>Under the Dome</b> is the story of a small town that is suddenly and inexplicably sealed off from the rest of the world by an enormous transparent dome. The town's inhabitants must deal with surviving the post-apocalyptic conditions while searching for answers about the dome, where it came from and if and when it will go away.</p>","updated":1573667713,"_links":{"self":{"href":"https://api.tvmaze.com/shows/1"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/185054"}}}},
    {
        "score":34.162006,
        "show":{"id":15,"url":"https://www.tvmaze.com/shows/15/constantine","name":"Constantine","type":"Scripted","language":"English","genres":["Drama","Action","Horror", "Crime"],"status":"Ended","runtime":60,"premiered":"2014-10-24","officialSite":"https://www.nbc.com/constantine","schedule":{"time":"20:00","days":["Friday"]},"rating":{"average":7.5},"weight":83,"network":{"id":1,"name":"NBC","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":38109,"thetvdb":273690,"imdb":"tt3489184"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/154.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/154.jpg"},"summary":"<p>Based on the wildly popular comic book series \"Hellblazer\" from DC Comics, seasoned demon hunter and master of the occult John Constantine is armed with a ferocious knowledge of the dark arts and a wickedly naughty wit. He fights the good fight - or at least he did. With his soul already damned to hell, he's decided to abandon his campaign against evil until a series of events thrusts him back into the fray, and he'll do whatever it takes to protect the innocent. With the balance of good and evil on the line‎, <b>Constantine </b>will use his skills to travel the country, find the supernatural terrors that threaten our world and send them back where they belong. After that, who knows... maybe there's hope for him and his soul after all.</p>","updated":1603789444,"_links":{"self":{"href":"https://api.tvmaze.com/shows/15"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/122719"}}}},
    {
        "score":29.162006,
        "show":{"id":20,"url":"https://www.tvmaze.com/shows/20/the-strain","name":"The Strain","type":"Scripted","language":"English","genres":["Drama","Horror","Thriller", "Action"],"status":"Ended","runtime":60,"premiered":"2014-07-13","officialSite":"http://www.fxnetworks.com/thestrain","schedule":{"time":"22:00","days":["Sunday"]},"rating":{"average":7.5},"weight":93,"network":{"id":13,"name":"FX","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":33229,"thetvdb":276564,"imdb":"tt2654620"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/70/175363.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/70/175363.jpg"},"summary":"<p><b>The Strain</b> is a high-concept thriller that tells the story of Dr. Ephraim Goodweather, the head of the Center for Disease Control Canary Team in New York City. He and his team are called upon to investigate a mysterious viral outbreak with hallmarks of an ancient and evil strain of vampirism. As the strain spreads, Goodweather, his team, and an assembly of everyday New Yorkers wage war for the fate of humanity itself.</p>","updated":1604405184,"_links":{"self":{"href":"https://api.tvmaze.com/shows/20"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1128366"}}}},
    {
        "score":33.162006,
        "show":{"id":37,"url":"https://www.tvmaze.com/shows/37/intruders","name":"Intruders","type":"Scripted","language":"English","genres":["Drama","Fantasy","Thriller", "Crime", "Science-Fiction"],"status":"Ended","runtime":60,"premiered":"2014-08-23","officialSite":"http://www.bbc.co.uk/programmes/b04nf78f","schedule":{"time":"22:00","days":["Saturday"]},"rating":{"average":6.9},"weight":79,"network":{"id":15,"name":"BBC America","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":38479,"thetvdb":277500,"imdb":"tt3552166"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/126/316698.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/126/316698.jpg"},"summary":"<p>A contemporary, chilling, paranormal tale set in the moody Pacific Northwest, the series spins a fascinating and complex web of drama. As strange, apparently unrelated events start happening, multiple story-lines - a missing wife, an assassin covering his crimes, a child on the run - begin to intertwine to reveal a conspiracy that will forever change our understanding of human nature.</p>","updated":1574217527,"_links":{"self":{"href":"https://api.tvmaze.com/shows/37"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1808"}}}},
    {
        "score":17.162006,
        "show":{"id":30,"url":"https://www.tvmaze.com/shows/30/american-horror-story","name":"Horror Story","type":"Scripted","language":"English","genres":["Drama","Horror","Thriller", "Crime"],"status":"Running","runtime":60,"premiered":"2011-10-05","officialSite":"http://www.fxnetworks.com/shows/american-horror-story","schedule":{"time":"22:00","days":["Wednesday"]},"rating":{"average":7.8},"weight":97,"network":{"id":13,"name":"FX","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":28776,"thetvdb":250487,"imdb":"tt1844624"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/282/706314.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/282/706314.jpg"},"summary":"<p><b>American Horror Story </b>is an horror television anthology series. Each season is conceived as a self-contained miniseries, following a disparate set of characters and settings, and a storyline with its own beginning, middle, and end. While some actors appear for more than one year, they play completely different roles in each season.</p>","updated":1611859115,"_links":{"self":{"href":"https://api.tvmaze.com/shows/30"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1696375"}}}},
    {
        "score":20.162006,
        "show":{"id":50,"url":"https://www.tvmaze.com/shows/50/the-lottery","name":"The Lottery","type":"Scripted","language":"English","genres":["Drama","Science-Fiction","Thriller"],"status":"Ended","runtime":60,"premiered":"2014-07-20","officialSite":null,"schedule":{"time":"22:00","days":["Sunday"]},"rating":{"average":6.5},"weight":0,"network":{"id":18,"name":"Lifetime","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":37857,"thetvdb":278447,"imdb":"tt3314228"},"image":{"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/146/366444.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/146/366444.jpg"},"summary":"<p>Set within a dystopian future driven by a global fertility crisis, <b>The Lottery </b>reveals a world staring down the barrel of impending extinction as women have mysteriously stopped bearing children. After years of research, Dr. Alison Lennon and her team remarkably fertilize 100 embryos. However, her victory is short-lived when the Director of the U.S. Fertility Commission, Darius Hayes, takes government control of the lab and informs the President of the monumental scientific breakthrough. To determine which women will carry the prized embryos to term, Chief of Staff Vanessa Keller convinces the President to hold a national lottery and a battle over the control of the 100 embryos begins.</p>","updated":1574364321,"_links":{"self":{"href":"https://api.tvmaze.com/shows/50"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2045"}}}}
    
]    

export default showData;